# Generated by Django 4.1.3 on 2023-07-02 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vada_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicles_type', models.CharField(max_length=50)),
                ('vehicles_rate', models.FloatField()),
                ('vehicles_image', models.CharField(max_length=100)),
                ('vehicles_no', models.CharField(max_length=100, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vada_app.category')),
            ],
        ),
    ]
