# Generated by Django 4.1.3 on 2023-07-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vada_app', '0002_vehicles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='vehicles_image',
            field=models.FileField(null=True, upload_to='static/uploads'),
        ),
    ]
