# Generated by Django 4.1.3 on 2023-07-12 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vada_app', '0004_contact'),
        ('userpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_now',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Departure_date', models.DateField()),
                ('Pickup_location1', models.CharField(max_length=100)),
                ('Dropoff_location1', models.CharField(max_length=100)),
                ('Return_date', models.DateField()),
                ('Pickup_location2', models.CharField(max_length=100)),
                ('Dropoff_location2', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vada_app.vehicles')),
            ],
        ),
    ]
